### ISSUE TITLE
Accept commands from same stream as data

### ISSUE THREAD

**Issue by miccio-dk** [erikbrntsn/python-live-plotting-from-data-stream#1]
Right now the user can submit commands (take screenshot, export data, rescale, pause...) through the keyboard.
It would be nice to be able to do the same thing from the same stream from which the data is read (being it serial, or TCP socket..).

**Comment by erikbrntsn** [comment]
This is should now be possible

**Comment by erikbrntsn** [comment]
Note that data might be lost e.g. if too much data is comming in, and thus the incomming commands might be lost as well

**Comment by miccio-dk** [comment]
thanks!
