### ISSUE TITLE
Specify line plots with parameter

### ISSUE THREAD

**Issue by ostenh** [erikbrntsn/python-live-plotting-from-data-stream#8]
It would be nice to be able to choose between line and dots for the plotting. 
Both lines and plot would be nice to have at the same time, so you easily can see the datapoints you get in.

An example of a way to choose could be to always default to dot plot, but having these to parameter to the plot.
**--line** _(Adds the line on the top of the dots)_
**--line-only**  _(Only draws the line)_

**Comment by erikbrntsn** [comment]
The only problem at the moment is that the data is stored in a ring buffer. This means there will be a line drawn across the entire plot. This can be solved either by splitting the actual plot call in two or by adding a None in between the left most and the right most data point. Both are pretty simple solutions

**Comment by erikbrntsn** [comment]
Done :)
You can now pass a line style argument to the plotter class such as '.-' or '-'. Default is '.'.
